---
title: "Data_Preperation"
author: "Martin Krahl"
date: "2023-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(dplyr)
library(lubridate)
library(ggplot2)
library(gridExtra)
library(tidyr)
library(data.table)
library(zoo)
library(timeDate)
library(corrplot)
library(caret)
library(stringr)
library(randomForest)
```
#Load Data
```{r}
df_Leads <- readxl::read_xlsx('./data/TermPaperChallenge.xlsx', sheet <- 'Leads')
df_Ads <- readxl::read_xlsx('./data/TermPaperChallenge.xlsx', sheet <- 'Ads')
df_Traffic <- readxl::read_xlsx('./data/TermPaperChallenge.xlsx', sheet <- 'WebsiteTraffic')
df_Macro <- readxl::read_xlsx('./data/TermPaperChallenge.xlsx', sheet <- 'Macro')
```

#Data Preprocessing (Leads Data)
```{r}
#Deleting Outliers
#Some observations have uniquely high value. These must be deleted to not effect the regression too much

#The EDA showed that the number of Leads is increasing over time. To allow for a flexible mean and sd, the measures are calculated by year. 
df_Leads <- df_Leads %>%
  mutate(Year = format(DateCreated, "%Y"))

summary_data <- df_Leads %>%
  group_by(Year, Type)%>%
  summarise(Mean_NextDayLeads = mean(NextDayLeads),
            Sd_NextDayLeads = sd(NextDayLeads),
            Threshold = Mean_NextDayLeads + 4 * Sd_NextDayLeads) %>%  #Threshold is determined to begin 4 Sd over the Mean
  select(Year, Type, Threshold)

df_Leads <- merge(df_Leads, summary_data, by = c("Year", "Type"))

df_Leads <- df_Leads %>%
  filter( DateCreated > max(df_Leads$DateCreated) %m-% months(2) | Threshold > NextDayLeads) %>%
  select(-Year, -Threshold)

# Add columns NextDayLeads for each Manual and Website with date 
data <- df_Leads %>%
  pivot_wider(names_from = Type, values_from = NextDayLeads) %>%
  rename(Date = DateCreated, #Rename columns
         NextDayLeads.Manual = Manual,
         NextDayLeads.Website = Website)

```

#Data Preproccesing (Traffic Data)
```{r}
#The Traffic Data started late. The first rows which are wrongfully zero have to be deleted. 
df_Traffic <- df_Traffic[which(df_Traffic$Visits != 0)[1]:nrow(df_Traffic), ]
```

#Data Prepoccessing (Macro-Economic Data)
```{r}
df_Macro <- df_Macro %>%
  complete(Date = seq(min(Date), max(Date), by = "day"))

#Fill the Macro-Economic Data with the previous values in case of empty values (weekends)
df_Macro <- df_Macro %>%
  fill(DAX,
       `Bundesanleihen 10 Year`,
       `Gold (in Euro)`,
       `German Electricity Price`,
       `Oilprice (Brent)`,
       `Federal Funds Futures (Expectations in 12 Months)`,
       `Job Postings in Germany on Indeed`, 
       `US Economic Policy Uncertainty Index`,
       `Baltic Exchange Dry Index (BDI)`,
       `Yield Spread 10Y - 2Y (Germany)`, 
       `Yield Spread 10Y - 2Y (US)`,
       `Exchange Rate (1 USD = X EUR)`, 
       `US Corporate Bonds - Investment Grade - Option Adjusted Spread`,
       .direction = "down")

#Converting/Replacing special characters
colnames(df_Macro) <- gsub(" ", "_", colnames(df_Macro))
colnames(df_Macro) <- gsub("[\\(\\)=\\-]", "", colnames(df_Macro))
```

### Feature Engineering
```{r}
#Idea: Add new features and select relevant ones later.

# group ad data by day and sum up clicks, impressions and money spend per day
df_Ads <- df_Ads %>%
  group_by(Date) %>%
  summarise(AdImpressions = sum(Impressions),
            AdClicks= sum(Clicks),
            AdSpend= sum(Spend))

# Add 7 and 30 day rolling Average for Impressions, Clicks and Spend.
df_Ads = cbind(df_Ads, AdImpressions.7RA = rollapplyr(df_Ads$AdImpressions, 7, mean, partial = TRUE)) 
df_Ads = cbind(df_Ads, AdClicks.7RA = rollapplyr(df_Ads$AdClicks, 7, mean, partial = TRUE)) 
df_Ads = cbind(df_Ads, AdSpend.7RA = rollapplyr(df_Ads$AdSpend, 7, mean, partial = TRUE)) 


# Add 7 day rolling Average for Visits and TimeSpent
df_Traffic = cbind(df_Traffic, Visits.7RA = rollapplyr(df_Traffic$Visits, 7, mean, partial = TRUE)) 
df_Traffic = cbind(df_Traffic, TimeSpent.7RA = rollapplyr(df_Traffic$TimeSpent, 7, mean, partial = TRUE)) 
```

```{r}
# Add 7 and 30 day rolling Average for NextDayLeads for each Manual and Website Leads.
data = data %>%
  mutate(NextDayLeads.Manual.1RA = lag(NextDayLeads.Manual),
         NextDayLeads.Website.1RA = lag(NextDayLeads.Website),
         NextDayLeads.Manual.4RA = rollapplyr(NextDayLeads.Manual.1RA, 4, mean, partial = TRUE, na.rm = T), # 7 day RA for Manual Leads
         NextDayLeads.Manual.7RA = rollapplyr(NextDayLeads.Manual.1RA, 7, mean, partial = TRUE, na.rm = T), # 30 day RA for Manual Leads
         NextDayLeads.Website.4RA = rollapplyr(NextDayLeads.Website.1RA, 4, mean, partial = TRUE, na.rm = T), # 7 day RA for Website
         NextDayLeads.Website.7RA = rollapplyr(NextDayLeads.Website.1RA, 7, mean, partial = TRUE, na.rm = T)) %>% # 30 day RA for Website Leads
  select(-NextDayLeads.Manual.1RA, -NextDayLeads.Website.1RA)
```

#Data Merging
```{r}
#All Joins are Inner Joins. This way we avoid N/A values in the predictor columns. 
# Merging Website Traffic data 
data = merge(data, df_Traffic, by="Date")
# Merging Macro data 
data = merge(data, df_Macro, by="Date")
# Merging Ad data 
data = merge(data, df_Ads, by="Date")
```

#Feature Engineering based on Date
```{r}
# Add Boolean feature IsNextDayWorkDay, which indicates if the NEXT day is a workday (not a weekend or a holiday). Needs Package timeDate. Also add Month Factor Feature

# Get official German Holidays (only country wide)
holidaysDE = holiday(year= c(2020,2021,2022,2023), Holiday = listHolidays("DE"))
# add column indicating if the next day is a work day and month variable
data <- data %>% 
  mutate(isNextDayWorkDay = if_else(isBizday(as.timeDate(as.Date(Date)+1),holidays = holidaysDE, wday = 1:5), 1, 0),
         month = factor(month(Date), labels = month.name))

```

#Split Data frames for Manual and Website
```{r}
data_manual <- data %>%
  select(-NextDayLeads.Website) %>%
  filter(!is.na(NextDayLeads.Manual))

data_website <- data %>%
  select(-NextDayLeads.Manual) %>%
  filter(!is.na(NextDayLeads.Website))
```


#Feature Engineering with rollapply() function
```{r}
#The following graph illustrates how we came up with the rollapply() arguments. The result was then paste into the code above. 
df <- data_manual %>%
  select(-NextDayLeads.Manual.4RA, -NextDayLeads.Manual.7RA, -NextDayLeads.Website.4RA, -NextDayLeads.Website.7RA) %>%
  mutate(NextDayLeads.Manual.1RA = lag(NextDayLeads.Manual))

s_window <- seq(1, 31, 2)
df_test <- tail(df, 90) 
df_train <- head(df, -90) %>% tail(-1)

width_model <- function(s_window, df_train, df_test) {
prec_results <- data.frame(width = numeric(0), rmse_train = numeric(0), rmse_test = numeric(0))

for (width in s_window) {
  #Create leadsLastWeek
  df_train <- df_train %>%
  mutate(leadsLastWeek = rollapply( NextDayLeads.Manual.1RA, width = width, FUN = sum, align = "right", partial = T))
  df_test <- df_test %>%
  mutate(leadsLastWeek = rollapply( NextDayLeads.Manual.1RA, width = width, FUN = sum, align = "right", partial = T))
  # Fit random forest model on training data
  lm_model <- lm(NextDayLeads.Manual ~ . 
                 -NextDayLeads.Manual.1RA -Date,
                 data = df_train)
  
  # Make predictions on Train & Test Data
  pred_train <- df_train %>%
  transmute(NextDayLeads.Manual,
            yhat = predict(lm_model, newdata <- df_train))

  pred_test <- df_test %>%
  transmute(NextDayLeads.Manual,
            yhat = predict(lm_model, newdata <- df_test))
 
  # Calculate Train & Test RMSE
  rmse_train <- sqrt( mean((pred_train$yhat - pred_train$NextDayLeads.Manual)^2))
  rmse_test <- sqrt( mean((pred_test$yhat - pred_test$NextDayLeads.Manual)^2))

 
    # Append results to the prec_results data frame
  prec_results <- rbind(prec_results, data.frame(width = width, train_rmse = rmse_train, test_rmse = rmse_test))
  }
return(prec_results)
}

window_values <- width_model(s_window, df_train, df_test)

# Plot precision and specificity of the train and test data. 
window_values %>%
  ggplot(aes(x = width)) +
  geom_line(aes(y = train_rmse, color = "Train RMSE")) +
  geom_line(aes(y = test_rmse, color = "Test RMSE")) +
  scale_color_manual(values = c("Train RMSE" = "blue", "Test RMSE" = "red")) +
  labs(x = "Width", y = "RMSE", color = "RMSE Type") +
  ggtitle("Train/Test RMSE  vs. width") +
  theme(
  plot.title = element_text(size = 14),
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 10),
  panel.background = element_rect(fill = "white", color = NA),
  panel.grid.major = element_line(color = "gray80"),
  panel.grid.minor = element_line(color = "gray90"),
  panel.border = element_blank())
```

```{r}
#Clean up workspace
rm(list = setdiff(ls(), c("data_manual", "data_website")))
```


```{r}
#The following graph shows the hyperparametric tuning for the number of trees
s_ntrees <- c(2, 4, 13, seq(1, 101, 5))
df_test <- tail(data_manual, 90) 
df_train <- head(data_manual, -90) %>% tail(-1)

ntree_rf_model <- function(s_ntrees, df_train, df_test) {
prec_results <- data.frame(ntree = numeric(0), rmse_train = numeric(0), rmse_test = numeric(0))

for (ntree in s_ntrees) {
  # Fit random forest model on training data
  rf_model <- randomForest(NextDayLeads.Manual ~ .
                          -Date, 
                          data = df_train, 
                          ntree = ntree,
                          mtry = round((ncol(df_train) - 2)*0.3),)
  
  # Make predictions on Train & Test Data
  pred_train <- df_train %>%
  transmute(NextDayLeads.Manual,
            yhat = predict(rf_model, newdata <- df_train))

  pred_test <- df_test %>%
  transmute(NextDayLeads.Manual,
            yhat = predict(rf_model, newdata <- df_test))
  
  # Calculate Train & Test RMSE
  rmse_train <- sqrt( mean((pred_train$yhat - pred_train$NextDayLeads.Manual)^2))
  rmse_test <- sqrt( mean((pred_test$yhat - pred_test$NextDayLeads.Manual)^2))

 
    # Append results to the prec_results data frame
  prec_results <- rbind(prec_results, data.frame(ntree = ntree, train_rmse = rmse_train, test_rmse = rmse_test))
  }
return(prec_results)
}

ntree_values <- ntree_rf_model(s_ntrees, df_train, df_test)

# Plot precision and specificity of the train and test data. 
ntree_values %>%
  ggplot(aes(x = ntree)) +
  geom_line(aes(y = train_rmse, color = "Train RMSE")) +
  geom_line(aes(y = test_rmse, color = "Test RMSE")) +
  scale_color_manual(values = c("Train RMSE" = "blue", "Test RMSE" = "red")) +
  labs(x = "Ntree", y = "RMSE", color = "RMSE Type") +
  ggtitle("Train/Test RMSE  vs. ntree") +
  theme(
  plot.title = element_text(size = 14),
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 10),
  panel.background = element_rect(fill = "white", color = NA),
  panel.grid.major = element_line(color = "gray80"),
  panel.grid.minor = element_line(color = "gray90"),
  panel.border = element_blank())
```
